#!/usr/bin/env python3
"""Per-session LoRA training from grouped SFT distill data.

Input:
    tppm_train_distill.json  (grouped by session_id, generated by generate_sft_dataset.py)

Output:
    lora_adapters/{session_id}/  (one LoRA adapter per session)

Usage:
    python3 train_per_session_lora.py
    python3 train_per_session_lora.py --epochs 12 --skip-session psydial_d4_00000

GPU: RTX 4090 24GB.  Base model: Qwen3.5-9B (BF16, ~18GB).
LoRA: r=16, alpha=32, q/k/v/o, ≈1% trainable params → ~3GB additional VRAM.
"""

from __future__ import annotations

import argparse
import gc
import json
import math
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import torch
from datasets import Dataset
from peft import LoraConfig, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
from trl import SFTTrainer

try:
    from trl import SFTConfig

    _HAS_SFT_CONFIG = True
except ImportError:
    _HAS_SFT_CONFIG = False


# === Paths ===
DEFAULT_DISTILL_PATH = Path("/root/autodl-tmp/wangqihao/data_trans/tppm_train_distill.json")
DEFAULT_BASE_MODEL_DIR = Path("/root/autodl-tmp/wangqihao/base_model/Qwen3.5-9B")
DEFAULT_LORA_ROOT = Path("/root/autodl-tmp/wangqihao/data_trans/lora_adapters")

# === Training hyperparameters ===
DEFAULT_EPOCHS = 10
DEFAULT_LEARNING_RATE = 2e-4
DEFAULT_LORA_R = 16
DEFAULT_LORA_ALPHA = 32
DEFAULT_MAX_LENGTH = 2048

SYSTEM_PROMPT = (
    "你是一名拥有长期记忆能力的专业心理咨询师。"
    "请根据用户的话语，给予自然、温和、专业的回复。"
)


@dataclass
class SessionData:
    session_id: str
    source_index: int
    samples: list[dict[str, Any]]


def load_grouped_distill(path: Path) -> list[SessionData]:
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, list):
        raise ValueError("Distill data must be a list of session groups.")
    sessions: list[SessionData] = []
    for group in payload:
        sessions.append(
            SessionData(
                session_id=str(group["session_id"]),
                source_index=int(group.get("source_index", -1)),
                samples=group["samples"],
            )
        )
    return sessions


def build_messages(samples: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Convert raw samples to Qwen chat template messages."""
    messages_list: list[dict[str, Any]] = []
    for sample in samples:
        instruction = str(sample.get("instruction", "")).strip()
        output = str(sample.get("output", "")).strip()
        if not instruction or not output:
            continue
        messages_list.append(
            {
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": instruction},
                    {"role": "assistant", "content": output},
                ]
            }
        )
    return messages_list


def format_to_chat_text(
    messages_list: list[dict[str, Any]], tokenizer: Any
) -> Dataset:
    records: list[dict[str, str]] = []
    for item in messages_list:
        text = tokenizer.apply_chat_template(
            item["messages"],
            tokenize=False,
            add_generation_prompt=False,
        )
        records.append({"text": text})
    return Dataset.from_list(records)


def load_base_model_and_tokenizer(
    base_model_dir: Path,
) -> tuple[Any, Any]:
    tokenizer = AutoTokenizer.from_pretrained(
        str(base_model_dir),
        trust_remote_code=True,
        local_files_only=True,
    )
    if tokenizer.pad_token is None and tokenizer.eos_token is not None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        str(base_model_dir),
        device_map="auto",
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        local_files_only=True,
    )
    if hasattr(model, "config") and getattr(model.config, "use_cache", False):
        model.config.use_cache = False
    return model, tokenizer


def build_lora_config(r: int, alpha: int) -> LoraConfig:
    return LoraConfig(
        r=r,
        lora_alpha=alpha,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.0,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )


def build_training_args(output_dir: Path, num_epochs: int, lr: float) -> TrainingArguments:
    common = {
        "output_dir": str(output_dir),
        "per_device_train_batch_size": 1,
        "gradient_accumulation_steps": 4,
        "gradient_checkpointing": True,
        "bf16": True,
        "num_train_epochs": num_epochs,
        "learning_rate": lr,
        "logging_steps": 1,
        "save_strategy": "no",
        "report_to": [],
        "remove_unused_columns": False,
        "dataloader_drop_last": False,
    }
    if _HAS_SFT_CONFIG:
        return SFTConfig(
            **common,
            dataset_text_field="text",
            max_length=DEFAULT_MAX_LENGTH,
            packing=False,
        )
    return TrainingArguments(**common)


def train_one_session(
    session: SessionData,
    *,
    base_model_dir: Path,
    lora_root: Path,
    lora_r: int,
    lora_alpha: int,
    num_epochs: int,
    lr: float,
) -> Path:
    output_dir = lora_root / session.session_id
    if output_dir.exists():
        shutil.rmtree(output_dir, ignore_errors=True)

    messages_list = build_messages(session.samples)
    if not messages_list:
        raise ValueError(f"Session {session.session_id} has no valid samples after filtering.")

    model, tokenizer = load_base_model_and_tokenizer(base_model_dir)
    train_dataset = format_to_chat_text(messages_list, tokenizer)

    lora_config = build_lora_config(r=lora_r, alpha=lora_alpha)
    training_args = build_training_args(output_dir=output_dir, num_epochs=num_epochs, lr=lr)

    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        peft_config=lora_config,
        processing_class=tokenizer,
    )

    trainer.train()
    trainer.model.save_pretrained(str(output_dir))
    tokenizer.save_pretrained(str(output_dir))

    # Free memory before next session
    del model, tokenizer, trainer, train_dataset
    gc.collect()
    torch.cuda.empty_cache()

    return output_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train per-session LoRA adapters from SFT distill data.")
    parser.add_argument("--distill", type=Path, default=DEFAULT_DISTILL_PATH)
    parser.add_argument("--base-model", type=Path, default=DEFAULT_BASE_MODEL_DIR)
    parser.add_argument("--lora-root", type=Path, default=DEFAULT_LORA_ROOT)
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS)
    parser.add_argument("--lr", type=float, default=DEFAULT_LEARNING_RATE)
    parser.add_argument("--lora-r", type=int, default=DEFAULT_LORA_R)
    parser.add_argument("--lora-alpha", type=int, default=DEFAULT_LORA_ALPHA)
    parser.add_argument("--skip-session", type=str, action="append", default=None,
                       help="Session IDs to skip (can repeat).")
    parser.add_argument("--only-session", type=str, default=None,
                       help="Train only this session ID (smoke test).")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if not args.base_model.exists():
        print(f"[ERROR] Base model not found: {args.base_model}", file=sys.stderr)
        return 1

    sessions = load_grouped_distill(args.distill)
    print(f"[INFO] Loaded {len(sessions)} sessions from {args.distill}")

    skip_set = set(args.skip_session) if args.skip_session else set()
    if args.only_session:
        sessions = [s for s in sessions if s.session_id == args.only_session]
        if not sessions:
            print(f"[ERROR] Session {args.only_session} not found.", file=sys.stderr)
            return 1

    total_samples = sum(len(s.samples) for s in sessions)
    print(f"[INFO] Sessions to train: {len(sessions)}, total samples: {total_samples}")
    print(f"[INFO] Base model: {args.base_model}")
    print(f"[INFO] LoRA output root: {args.lora_root}")
    print(f"[INFO] Epochs per session: {args.epochs}, LR: {args.lr}")
    print(f"[INFO] LoRA r={args.lora_r}, alpha={args.lora_alpha}")

    for idx, session in enumerate(sessions, 1):
        if session.session_id in skip_set:
            print(f"[SKIP] {session.session_id}")
            continue

        n_samples = len(session.samples)
        print(f"\n{'='*60}")
        print(f"[TRAIN] [{idx}/{len(sessions)}] session={session.session_id} "
              f"samples={n_samples}")
        print(f"{'='*60}")

        try:
            output_dir = train_one_session(
                session,
                base_model_dir=args.base_model,
                lora_root=args.lora_root,
                lora_r=args.lora_r,
                lora_alpha=args.lora_alpha,
                num_epochs=args.epochs,
                lr=args.lr,
            )
            print(f"[DONE] Saved adapter: {output_dir}")
        except Exception as exc:
            print(f"[ERROR] Session {session.session_id} failed: {exc}", file=sys.stderr)
            continue

    print(f"\n[DONE] All sessions processed. Adapters saved under: {args.lora_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
